template:
  - sensor:
      - name: "Battery net power"
        unique_id: battery_power_net
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set discharge_w = (states('sensor.battery_consumption_power') | float(0)) * 1000 %}
          {% set charge_w = (states('sensor.battery_injection_power') | float(0)) * 1000 %}
          {{ (charge_w - discharge_w) | round(0) }}

      - name: "Battery charging power"
        unique_id: battery_charging_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set charge_w = (states('sensor.battery_injection_power') | float(0)) * 1000 %}
          {{ (charge_w if charge_w > 0 else 0) | round(0) }}

      - name: "Battery discharging power"
        unique_id: battery_discharging_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set discharge_w = (states('sensor.battery_consumption_power') | float(0)) * 1000 %}
          {{ (discharge_w if discharge_w > 0 else 0) | round(0) }}

      # Net to grid: + = export, - = import
      - name: "Grid net power"
        unique_id: grid_net_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set imp_w = (states('sensor.grid_consumption_power') | float(0)) * 1000 %}
          {% set exp_w = (states('sensor.grid_injection_power') | float(0)) * 1000 %}
          {{ (exp_w - imp_w) | round(0) }}

      # PV self-consumption (approx): production - export
      - name: "PV self-consumed power"
        unique_id: pv_self_consumed_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set pv_w  = (states('sensor.panel_production_power') | float(0)) * 1000 %}
          {% set exp_w = (states('sensor.grid_injection_power') | float(0)) * 1000 %}
          {{ max(0, pv_w - exp_w) | round(0) }}

      # Share of current house load covered by PV (0-100%)
      - name: "PV cover now"
        unique_id: pv_cover_now
        unit_of_measurement: "%"
        state: >
          {% set load_w = (states('sensor.house_load_power') | float(0)) * 1000 %}
          {% set pv_w   = (states('sensor.panel_production_power') | float(0)) * 1000 %}
          {% if load_w > 0 %}
            {{ (min(1, pv_w / load_w) * 100) | round(0) }}
          {% else %}
            0
          {% endif %}

      # Instant self-sufficiency: 100% if you're not importing
      - name: "Self-sufficiency now"
        unique_id: self_sufficiency_now
        unit_of_measurement: "%"
        state: >
          {% set load_w = (states('sensor.house_load_power') | float(0)) * 1000 %}
          {% set imp_w  = (states('sensor.grid_consumption_power') | float(0)) * 1000 %}
          {% if load_w > 0 %}
            {{ ((1 - min(1, imp_w / load_w)) * 100) | round(0) }}
          {% else %}
            0
          {% endif %}

      - name: "Energy mode"
        unique_id: energy_mode
        state: >
          {% set pv_w   = (states('sensor.panel_production_power') | float(0)) * 1000 %}
          {% set imp_w  = (states('sensor.grid_consumption_power') | float(0)) * 1000 %}
          {% set exp_w  = (states('sensor.grid_injection_power') | float(0)) * 1000 %}
          {% set chg_w  = states('sensor.battery_charging_power') | float(0) %}
          {% set dis_w  = states('sensor.battery_discharging_power') | float(0) %}
        
          {# thresholds in W #}
          {% set grid_thr = 50 %}
          {% set batt_thr = 50 %}
          {% set pv_thr   = 50 %}
       
          {% if exp_w > grid_thr %}
            {% if chg_w > batt_thr %}
              ðŸŒžðŸ“¤ðŸ”‹ Exporting + battery charging
            {% elif dis_w > batt_thr %}
              ðŸŒžðŸ“¤ðŸ”‹ Exporting + battery discharging
            {% else %}
              ðŸŒžðŸ“¤ Exporting
            {% endif %}
        
          {% elif imp_w > grid_thr %}
            {% if chg_w > batt_thr %}
              ðŸŒ™ðŸ“¥ðŸ”‹ Importing + battery charging
            {% elif dis_w > batt_thr %}
              ðŸŒ™ðŸ“¥ðŸ”‹ Importing + battery discharging
            {% else %}
              ðŸŒ™ðŸ“¥ Importing
            {% endif %}
        
          {% else %}
            {% if chg_w > batt_thr %}
              ðŸ”‹â¬†ï¸ Battery charging
            {% elif dis_w > batt_thr %}
              ðŸ”‹â¬‡ï¸ Battery discharging
            {% elif pv_w > pv_thr %}
              ðŸŒ¤ï¸ PV running the home
            {% else %}
              ðŸ˜´ Quiet moment
            {% endif %}
          {% endif %}

  - sensor:
      - name: "Panel production power (W)"
        unique_id: panel_production_power_w
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set v = states('sensor.panel_production_power') %}
          {% if v in ['unknown','unavailable','none',''] %}
            {{ 0 }}
          {% else %}
            {{ (float(v) * 1000) | round(0) }}
          {% endif %}

sensor:
  - platform: integration
    source: sensor.house_load_power
    name: House load energy
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.grid_consumption_power
    name: Grid import energy
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.grid_injection_power
    name: Grid export energy
    unit_prefix: k
    round: 2
  - platform: integration
    source: sensor.panel_production_power
    name: PV energy
    unit_prefix: k
    round: 2
